name: spring_pulldown_menu_example
description: Example app for the spring_pulldown_menu package.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  spring_pulldown_menu:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
